# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUKKtsYq51-Ja45uu7zCnLwuMgFXOVyS
"""

import random

# Instructions
print('Winning rules of the game ROCK PAPER SCISSORS are:\n'
      + "Rock vs Paper -> Paper wins \n"
      + "Rock vs Scissors -> Rock wins \n"
      + "Paper vs Scissors -> Scissors wins \n")

# Initializing scores
user_wins = 0
computer_wins = 0

while True:
    print("\nEnter your choice: \n 1 - Rock \n 2 - Paper \n 3 - Scissors \n")

    # Taking user input
    choice = int(input("Enter your choice: "))

    # Ensuring input is valid
    while choice > 3 or choice < 1:
        choice = int(input("Enter a valid choice (1, 2, or 3): "))

    # Map choice to names
    if choice == 1:
        choice_name = 'Rock'
    elif choice == 2:
        choice_name = 'Paper'
    else:
        choice_name = 'Scissors'

    # Print user choice
    print('\nUser choice is:', choice_name)
    print("Now it's Computer's turn...")

    # Generating computer's choice
    comp_choice = random.randint(1, 3)
    if comp_choice == 1:
        comp_choice_name = 'Rock'
    elif comp_choice == 2:
        comp_choice_name = 'Paper'
    else:
        comp_choice_name = 'Scissors'

    print("Computer choice is:", comp_choice_name)
    print(choice_name, 'vs', comp_choice_name)

    # Determining the winner
    if choice == comp_choice:
        result = "DRAW"
    elif (choice == 1 and comp_choice == 2) or (comp_choice == 1 and choice == 2):
        result = 'Paper'
    elif (choice == 1 and comp_choice == 3) or (comp_choice == 1 and choice == 3):
        result = 'Rock'
    elif (choice == 2 and comp_choice == 3) or (comp_choice == 2 and choice == 3):
        result = 'Scissors'

    # Update scores and display the result
    if result == "DRAW":
        print("<== It's a tie! ==>")
    elif result == choice_name:
        print("<== User wins this round! ==>")
        user_wins += 1
    else:
        print("<== Computer wins this round! ==>")
        computer_wins += 1

    # Display scores
    print(f"\nCurrent Scores: User - {user_wins} | Computer - {computer_wins}")

    # Ask if the user wants to play again
    print("\nDo you want to play again? (Y/N)")
    ans = input().lower()
    if ans == 'n':
        break

# After exiting the loop, display the final scores
print("\nFinal Scores:")
print(f"User: {user_wins} | Computer: {computer_wins}")
if user_wins > computer_wins:
    print("Congratulations! You are the overall winner!")
elif user_wins < computer_wins:
    print("Better luck next time! The computer wins overall.")
else:
    print("It's a tie overall! Great game.")

print("Thanks for playing!")